[package]
name = "x-clone"
version = "0.4.24"
edition = "2021"

[dependencies]
chrono = "0.4.39"
flate2 = "1.0.33"
futures = "0.3.30"
lazy_static = "1.5.0"
regex = "1.10.6"
reqwest = "0.12.7"
serde = "1.0.209"
serde_derive = "1.0.209"
serde_json = "1.0.128"
tar = "0.4.41"
tokio = { version = "1.40.0", features = ["full"] }
